### ISSUE TITLE
[Bug]: Lambda Execution Hangs After Handler Response Return When Using Extension With No API Key

### ISSUE THREAD

**Issue by rod-dvla** [instana/nodejs#976]
### Problem Description

When using the Extension with no api key configured (tested with Node 18) lambda invocation takes an additional 1.2 seconds.  Its worth noting that the time taken for the request handler to return response to a caller does not increase, but after the handler returns response the lambda hangs for a period of time.

Was able to reproduce the issue with a vanilla handler on new serverless app.  Two handlers, one with and the other without the layer.

Handler Config:

![Screenshot 2023-12-18 at 17 28 23](https://github.com/instana/nodejs/assets/71075448/711cdad2-3587-45f2-86f0-37b5fa621f99)

![Screenshot 2023-12-18 at 17 28 47](https://github.com/instana/nodejs/assets/71075448/0544835d-c8e8-46ce-b6d5-d981d1977999)

Invocation times with extension:

![Screenshot 2023-12-18 at 17 27 52](https://github.com/instana/nodejs/assets/71075448/ee98af9c-bce9-4b37-8a26-6a229994a8dd)

Invocation times without extension:

![Screenshot 2023-12-18 at 17 28 01](https://github.com/instana/nodejs/assets/71075448/30d64c9e-547a-48cb-8bd7-a1e0e0ccfad9)

I found this issue in our production environments, when disabling the lambda extension.  In this case there is no reason for data to be sent to the extension, nor for the extension to be holding the handler for an additional period of time.

Hope you are able to help, many thanks and all the best.

### Short, Self Contained Example

Create New Serverless App (Node18), two seperate handlers.  Configure one lambda to use the layer (tested with layer version 168 and 171).  Set LAMBDA_HANDLER env var pointing at your handler and using instana-aws-lambda-auto-wrap.handler, no other environment variables set. 

The other configured to use the handler directly (no Instana extension or env variables either).

Call each and note the difference in lambda duration (not api latency).

### Node.js Version

Node 18

### package.json

```shell
No Package.json required.
```

### package-lock.json

```shell
No package-lock.json required.
```

**Comment by aryamohanan** [comment]
@rod-dvla Thanks for your report. We are taking a look.

**Comment by aryamohanan** [comment]
@rod-dvla Based on your message, we understand that when you disable the lambda extension, the duration significantly increases, causing the handler to be held for an additional period. Please correct us if we are wrong.

We have been unable to replicate the issue on our end. Could you kindly share the logs to help us gather more information? 

Additionally, could you provide information on the steps you take to disable the extension?

Here's what we've attempted so far:

1. Created a lambda function (node18) without the extension and no api keys in CommonJS.
2. Created a lambda function  (node18) with the extension and no api key in CommonJS, setting the LAMBDA_HANDLER to `instana-aws-lambda-auto-wrap.handler`, with no other environment variables configured.
3. Invoked the endpoints multiple times and monitored the durations.

Upon reviewing the logs, we have not identified the reported issue.

Note: To produce logs, you can utilize the environment variable `INSTANA_DEBUG` with the value set to `debug`.

**Comment by kirrg001** [comment]
@rod-dvla Do you experience that under load?

**Comment by rod-dvla** [comment]
@kirrg001 I get this on each request regardless of load.  

@aryamohanan Will look to set INSTANA_DEBUG and get the info back to you today.

**Comment by rod-dvla** [comment]
Have collected log output for an endpoint with extension and INSTANA_DEBUG set to debug:

[log-events-viewer-result(8).csv](https://github.com/instana/nodejs/files/13741899/log-events-viewer-result.8.csv)

For reference have also included the log output for function without.

[log-events-viewer-result(9).csv](https://github.com/instana/nodejs/files/13741893/log-events-viewer-result.9.csv)

This is for a serverless stack with 2 files:

serverless.yml
```
service: basic-instana-extension-test

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-2

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /instana/without
          method: get
  with-instana-extension:
    handler: instana-aws-lambda-auto-wrap.handler
    environment:
      LAMBDA_HANDLER: handler.hello
      INSTANA_DEBUG: debug
    layers:
      - arn:aws:lambda:eu-west-2:410797082306:layer:instana-nodejs:171
    events:
      - httpApi:
          path: /instana/with
          method: get
```

handler.js
```
'use strict';

module.exports.hello = async (event) => {
  return {
    statusCode: 200,
    body: JSON.stringify(
      {
        message: 'Go Serverless v1.0! Your function executed successfully!',
        input: event,
      },
      null,
      2
    ),
  };

  // Use this code if you don't use the http event with the LAMBDA-PROXY integration
  // return { message: 'Go Serverless v1.0! Your function executed successfully!', event };
};

```

Note the duration of the lambda is much higher (1500sec odd).  From what I've seen api response latency is roughly the same with/without extension, but the lambda duration is a lot higher on the version with extension.
